language: node_js
sudo: required
node_js:
- 7.9.0
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- npm install -g hexo-cli
install:
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo generate
after_script:
- git config user.name "yuyu"
- git config user.email "yuy9501@126.com"
- sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
- hexo deploy
